Models/ApiHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace FoodTruckFinderWebApp.Models
{
    public static class ApiHelper
    {
        public static HttpClient ApiClient { get; set; }

        /// <summary>
        /// Initialize a connection. Sets the base address and request headers.
        /// </summary>
        public static void InitializeClient()
        {
            ApiClient = new HttpClient();
            ApiClient.BaseAddress = new Uri("https://data.sfgov.org/");
            ApiClient.DefaultRequestHeaders.Accept.Clear();
            ApiClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace FoodTruckFinderWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FoodTruckModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodTruckFinderWebApp.Models
{
    public class FoodTruckModel
    {
        public int DayOrder { get; set; }
        public string DayOfWeek { get; set; }
        public string Location { get; set; }
        public string Start24 { get; set; }
        public string End24 { get; set; }
        public string Applicant { get; set; }
    }
}

Models/FoodTruckProcessor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace FoodTruckFinderWebApp.Models
{
    class FoodTruckProcessor
    {
        /// <summary>
        /// Aynchronous function for fetching results from the url string. Raises an exception if response was not successful.
        /// </summary>
        /// <returns> List of food trucks by the API</returns>
        public static async Task<List<FoodTruckModel>> LoadFoodTruckData(string url)
        {
            List<FoodTruckModel> foodTruck = null;
            using (HttpResponseMessage response = await ApiHelper.ApiClient.GetAsync(url))
            {
                if (response.IsSuccessStatusCode)
                {
                    foodTruck = await response.Content.ReadAsAsync<List<FoodTruckModel>>();
                    return foodTruck;
                }
                else
                {
                    throw new Exception(response.ReasonPhrase);
                }
            }
        }


        /// <summary>
        // Returns true if system day equal to food truck day order and system time between start and end time of food cart.
        /// </summary>
        /// <param name="currentSystemDayIndex">System day index 0:Sunday 1:Monday 2:Tuesday 3:Wednesday 4:Thursday 5:Friday 6:Saturday</param>
        /// <param name="currentSystemTime">System time in HH:MM format(24hr)</param>
        /// <param name="foodTruck">List of all food trucks</param>
        /// <returns>True if open and False if closed</returns>
        private static bool IsFoodTruckOpen(int currentSystemDayIndex, string currentSystemTime, FoodTruckModel foodTruck)
        {
            if (currentSystemDayIndex != foodTruck.DayOrder)
                return false;


            int systemTimeInMinutes = UtilityHelpers.ConvertToMinutes(currentSystemTime);
            int foodTruckStartTimeMinutes = UtilityHelpers.ConvertToMinutes(foodTruck.Start24);
            int foodTruckEndTimeMinutes = UtilityHelpers.ConvertToMinutes(foodTruck.End24);

            if (foodTruckStartTimeMinutes <= systemTimeInMinutes && foodTruckEndTimeMinutes > systemTimeInMinutes)
            {
                return true;
            }
            else
            {
                return false;
            }
        }


        /// <summary>
        /// Public function that returns a list of open food trucks sorted by applicant.
        /// </summary>
        /// <param name="currentSystemDayIndex">System day index 0:Sunday 1:Monday 2:Tuesday 3:Wednesday 4:Thursday 5:Friday 6:Saturday</param>
        /// <param name="currentSystemTime">System time in HH:MM format(24hr)</param>
        /// <param name="foodTrucks">List of all food trucks</param>
        /// <returns>List of FoodTruckModel</returns>
        public static List<FoodTruckModel> GetOpenFoodTrucks(int currentSystemDayIndex, string currentSystemTime, List<FoodTruckModel> foodTrucks)
        {
            List<FoodTruckModel> openFoodTrucks = new List<FoodTruckModel>();

            foreach (var foodTruck in foodTrucks)
            {
                if (IsFoodTruckOpen(currentSystemDayIndex, currentSystemTime, foodTruck))
                {
                    openFoodTrucks.Add(foodTruck);
                }
            }

            openFoodTrucks = openFoodTrucks.OrderBy(o => o.Applicant).ToList();

            return openFoodTrucks;
        }
    }
}

Models/UtilityHelpers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodTruckFinderWebApp.Models
{
    static class UtilityHelpers
    {
        /// <summary>
        /// Utility helper to convert time in HH::MM format into minutes.
        /// </summary>
        /// <param name="Time">HH:MM (24hr format)</param>
        /// <returns>total minutes</returns>
        public static int ConvertToMinutes(string Time)
        {
            var Parts = Time.Split(':');
            return Int32.Parse(Parts[0]) * 60 + Int32.Parse(Parts[1]);
        }

        /// <summary>
        /// Helper function to convert time to utc-8
        /// </summary>
        /// <param name="currentSystemTime"></param>
        /// <returns></returns>
        public static string ConvertToUtcMinus8(string currentSystemTime)
        {
            string result = "";
            var parts = currentSystemTime.Split(':');
            int hr = int.Parse(parts[0]);
            string minutes = parts[1];
            hr = (hr - 8) >= 0 ? (hr - 8) : 24 + (hr - 8);
            result = hr.ToString() + ":" + minutes;
            return result;
        }
    }
}

Controllers/FoodTruckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoodTruckFinderWebApp.Models;
using FoodTruckFinderWebApp.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace FoodTruckFinderWebApp.Controllers
{
    public class FoodTruckController : Controller
    {
        public IActionResult OpenFoodTrucks()
        {

            int currentSystemDayIndex = (int)System.DateTime.Now.DayOfWeek;
            string currentSystemTime = DateTime.Now.ToString("HH:mm", System.Globalization.DateTimeFormatInfo.InvariantInfo);

            //To Do: Cheat function to convert webserver time to UTC-8. Fix this.
            currentSystemTime = UtilityHelpers.ConvertToUtcMinus8(currentSystemTime);

            string url = "https://data.sfgov.org/resource/jjew-r69b.json";

            ApiHelper.InitializeClient();
            List<FoodTruckModel> allFoodTrucks = Task.Run(() => FoodTruckProcessor.LoadFoodTruckData(url)).Result;
            List<FoodTruckModel> openFoodTrucks = FoodTruckProcessor.GetOpenFoodTrucks(currentSystemDayIndex, currentSystemTime, allFoodTrucks);
            int maxPageCounter = (int)Math.Ceiling((decimal)openFoodTrucks.Count / 10);
            FoodTruckViewModel foodTruckViewModel = new FoodTruckViewModel
            {
                allFoodTrucks = allFoodTrucks,
                openFoodTrucks = openFoodTrucks,
                currentPageCounter = 1,
                maxPageCounter = maxPageCounter,
                currentSystemTime = currentSystemTime
            };

            return View(foodTruckViewModel);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FoodTruckFinderWebApp.Models;

namespace FoodTruckFinderWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/FoodTruck/OpenFoodTrucks.cshtml
@model FoodTruckFinderWebApp.ViewModel.FoodTruckViewModel
@{
    ViewData["Title"] = "OpenFoodTrucks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Open Food Trucks</h1>
<p> Current Server Time: @Model.currentSystemTime</p>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col">Open Time</th>
            <th scope="col">Close Time</th>
        </tr>
    </thead>

    <tbody id="OpenFoodTruckTable">
        @{int startIndex = Model.CalculateDisplayStartIndex();
            int endIndex = Model.CalculateDisplayEndIndex();}
        @for (int i = startIndex; i < endIndex; ++i)
        {
            <tr>
                <th scope="row">@Model.openFoodTrucks[i].Applicant</th>
                <td>@Model.openFoodTrucks[i].Location</td>
                <td>@Model.openFoodTrucks[i].Start24</td>
                <td>@Model.openFoodTrucks[i].End24</td>
            </tr>
        }
    </tbody>
</table>

<div id="NavigationBar">
    <ul class="pagination">
        @for (int i = 0; i < Model.maxPageCounter; i++)
        {
            if (i == startIndex)
            {
                <li class="page-item active">
                    <a class="page-link" onclick="RefreshTable((@i+1))" href="#">@(i + 1)</a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" onclick="RefreshTable(@(i + 1))" href="#">@(i + 1)</a>
                </li>
            }

        }
    </ul>
</div>

<script type="text/javascript">

    function CalculateDisplayStartEndIndex(pageIndex,maxFoodTruck)
    {
        var startIndex = (pageIndex - 1) * 10;
        var endIndex = Math.min(10 * pageIndex, maxFoodTruck);
        return {
            startIndex: startIndex,
            endIndex: endIndex,
        };
    }

    function RefreshTable(navOptionSelected)
    {
        console.log("Refresh Table Called with nav option selected: " + navOptionSelected);
        var foodTruckObj = @Html.Raw(Json.Serialize(@Model.openFoodTrucks));
        var indexes = CalculateDisplayStartEndIndex(navOptionSelected, foodTruckObj.length);
        var startIndex = indexes.startIndex;
        var endIndex = indexes.endIndex;
        console.log(foodTruckObj[0].location);

        var html = '';
        html += `<tbody>`;

        for (var i = startIndex; i < endIndex; i++)
        {
            html += `<tr>`;
            html += `<th>` + foodTruckObj[i].applicant + `</th>`;
            html += `<td>` + foodTruckObj[i].location + `</td>`;
            html += `<td>` + foodTruckObj[i].start24 + `</td>`;
            html += `<td>` + foodTruckObj[i].end24 + `</td>`;
            html += `</tr>`;
        }
        html += `</tbody>`;
        document.getElementById("OpenFoodTruckTable").innerHTML = html;

        RenderNavBar(navOptionSelected, foodTruckObj.length);
    }

    function RenderNavBar(navOptionSelected, maxFoodTruck)
    {
        var maxIndex = Math.ceil(maxFoodTruck / 10);
        var html = '';
        html += `<ul class="pagination">`;
        for (var i = 0; i < maxIndex; i++)
        {
            if (i == (navOptionSelected-1))
            {
                html += `<li class="page-item active">`;
            }
            else
            {
                html += `<li class="page-item">`
            }

            html += `<a class="page-link" onclick="RefreshTable(`+(i+1)+`)" href="#">` + (i + 1) + `</a>`;
            html += `</li>`;
        }
        html += `</ul>`
        document.getElementById("NavigationBar").innerHTML = html;

    }
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food Truck Finder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-materia.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="FoodTruck" asp-action="OpenFoodTrucks">Food Truck Finder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div class="container">
            &copy; 2019 - FoodTruckFinderWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>